name: FoxSigile
version: ${version}
main: pl.foxcraft.foxsigile.FoxSigilePlugin
api-version: '1.21'
author: DeXter
folia-supported: false
commands:
  sigile:
    description: Otwiera podgląd menu sigili lub zarządza slotami gracza.
    usage: /sigile [unlock|lock] [gracz] [all|1|2|3]
  sigileopen:
    description: Otwiera edytowalne menu sigili wybranemu graczowi.
    usage: /sigileopen <gracz>
    permission: foxsigile.admin
permissions:
  foxsigile.admin:
    description: Pozwala zarządzać slotami sigili innych graczy.
    default: op
